// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLAppML.Model
{
    public class ModelInput
    {
        [ColumnName("Sentiment"), LoadColumn(0)]
        public bool Sentiment { get; set; }


        [ColumnName("Body"), LoadColumn(1)]
        public string Body { get; set; }


    }
}
