// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using MLAppML.Model;

namespace MLAppML.ConsoleApp
{
	class Program
    {
        static void Main(string[] args)
        {
            // Add input data
            var input = new ModelInput();
            input.Body = "This dress was ugly and didn't fit.";

            // Load model and predict output of sample data
            ModelOutput result = ConsumeModel.Predict(input);
            Console.WriteLine($"Text: {input.Body}\nIs a good review: {result.Prediction}");
            Console.ReadLine();
        }
    }
}
